<?php

namespace WCSBundle\Repository;

/**
 * terrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class terrainRepository extends \Doctrine\ORM\EntityRepository
{
}
